### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by MaraScott** [audioscavenger/ComfyUI-Thumbnails#1]
![Screenshot_20240530_194009_com.discord.jpg](https://github.com/audioscavenger/ComfyUI-Thumbnails/assets/482210/115d923c-44ff-4f98-8447-1e1b4d401850)

**Comment by audioscavenger** [comment]
wow thanks for the feedback!! how do i reproduce? what is the size selector? do i just load these SDXL size picker nodes and load image and it should happen as described?

**Comment by audioscavenger** [comment]
okay i see the problem. these are also load image nodes, but they don't actually load existing images. they are supposed to show a list of sizes.
okay that is a problem indeed. let me see how i can exclude them
is there a list that you have already? i don't install all the nodes that exist on earth

**Comment by audioscavenger** [comment]
nvm i just fixed it, very simply:
`if (thisCurrentNode?.type !== "LoadImage") return ctx;`
