### ISSUE TITLE
Cant seem to get this to work....

### ISSUE THREAD

**Issue by Wprussell** [audioscavenger/ComfyUI-Thumbnails#5]
Loads fine, Im just not getting any thumbnails?   Really, works just like the stock one.....  

What am I missing here?

![Capture](https://github.com/user-attachments/assets/563d58ee-2386-4209-a5a0-c53886cd688d)

C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-16 12:39:01.133868
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\AI\ComfyUI\python_embeded\python.exe
** ComfyUI Path: C:\AI\ComfyUI\ComfyUI
** Log path: C:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.6 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 130813 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\AI\ComfyUI\ComfyUI\web
C:\AI\ComfyUI\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.19.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13900K - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 560.94
xFormers not available
xFormers not available
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
Total VRAM 16376 MB, total RAM 130813 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
### ComfyUI Revision: 2766 [7390ff3b] | Released on '2024-10-16'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.4.1+cu124
C:\AI\ComfyUI
############################################
C:\AI\ComfyUI\custom_nodes\ComfyUI-Universal-Styler\CSV
############################################
[]
############################################
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)

From Bmad Custom Nodes
 Loaded 125 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (50)
  + color clip ade20k node (1)
  + extension dependent nodes (2)

Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "The future depends on what you do today." - Mahatma Gandhi

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_SSStereoscope
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\tiled_ksampler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Stereopsis
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Thumbnails
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-FFmpeg
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.7 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]

**Comment by Piscabo** [comment]
Love to have this work, but it does not show any thumbnails. Is there a working version? (or fork?)

**Comment by audioscavenger** [comment]
as of today, i am looking into this. been away since June and now with a mortgage on my back. Not sure this is fixable after all I heard about the new ui.

**Comment by audioscavenger** [comment]
> thumbn

mostly fixed as of right now: v1.23
