### ISSUE TITLE
Console Eror after 'Thumbnails' added 

### ISSUE THREAD

**Issue by Piscabo** [audioscavenger/ComfyUI-Thumbnails#7]
'Thumbnails' Implementation causes this issue
![image](https://github.com/user-attachments/assets/442c1f4f-109a-4c0c-b35d-6a655c65942f)

**Comment by audioscavenger** [comment]
this is now fixed! for some reason, I have custom nodes that load _hashlib_ for me so I neglected to add it in the import section.
