### ISSUE TITLE
The latest version 1.26 cannot automatically display thumbnails. 1.25 prompts a hashlib error, so I can only go back to version 1.24. Please fix it.

### ISSUE THREAD

**Issue by kkjfb** [audioscavenger/ComfyUI-Thumbnails#8]
The latest version 1.26 cannot automatically display thumbnails. 1.25 prompts a hashlib error, so I can only go back to version 1.24. Please fix it.

**Comment by audioscavenger** [comment]
sorry to hear that. 
so I deleted ALL my custom nodes, I have zero other then the manager, proof:
![image](https://github.com/user-attachments/assets/df89dc64-49d8-432c-9432-6a5677984455)

Thumbnails still works perfectly 
please post any messages related to Thumbnails node you would see in the console log, and also debug is enabled in JS, 
hit F12 and look in the console, delete all lines, then click to select an image, see what's the output in the console, do you see any error or empty output?

**Comment by kkjfb** [comment]
> sorry to hear that. 很遗憾听到这个消息。 so I deleted ALL my custom nodes, I have zero other then the manager, proof:所以我删除了所有自定义节点，除了管理器之外我还有零个节点，证明： ![image](https://private-user-images.githubusercontent.com/3853962/396201449-df89dc64-49d8-432c-9432-6a5677984455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzMzOTUsIm5iZiI6MTczNDQzMzA5NSwicGF0aCI6Ii8zODUzOTYyLzM5NjIwMTQ0OS1kZjg5ZGM2NC00OWQ4LTQzMmMtOTQzMi02YTU2Nzc5ODQ0NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTA1ODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNlOTVjMWIxYmMxOGM1NTc0NmNhZGMwNzU4MDFmMjViMGU5MTRlODhkMjVkNThkY2Y5NzkyZjk4OGEzY2ZkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yb9s7PdbWTvhl-O0u7sZG-W0MO4FV0BayFEtaO0tZks)
> 
> Thumbnails still works perfectly缩略图仍然可以正常工作 please post any messages related to Thumbnails node you would see in the console log, and also debug is enabled in JS,请发布与缩略图节点相关的任何消息，您将在控制台日志中看到，并且在 JS 中启用了调试， hit F12 and look in the console, delete all lines, then click to select an image, see what's the output in the console, do you see any error or empty output?按 F12 并查看控制台，删除所有行，然后单击选择图像，查看控制台中的输出是什么，您是否看到任何错误或空输出？

Now it is back to normal. I upgraded from 1.24 to 1.26 and tested it again. This time it is normal! Thank you! Very good plugin!

**Comment by audioscavenger** [comment]
super appreciate your support, many thanks
